
const vegetables = [
  {
    name: "Carrot",
    category:	"vegetable",
    scientificName:	"Daucus carota",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 80,
    waterDemand:	"high",
    nutritionalNeeds: "small",
    perennial: false, 
  },
  {
    name: "Zucchini",
    category:	"vegetable",
    scientificName:	"Cucurbita pepo",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 75,
    waterDemand:	"medium",
    nutritionalNeeds: "medium",
    perennial: false, 
  },
  {
    name: "Onion",
    category:	"vegetable",
    scientificName:	"Allium cepa",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 110,
    waterDemand:	"medium",
    nutritionalNeeds: "medium",
    perennial: false, 
  },
  {
    name: "Garlic",
    category:	"vegetable",
    scientificName:	"Alium sativum",
    timeToSow: "autumn",
    directSowing: true,
    developmentTime: 300,
    waterDemand:	"high",
    nutritionalNeeds: "high",
    perennial: false, 
  },
]

const herbs = [
{
  name: "Parsley",
  category:	"Herbs",
  scientificName:	"Petroselinum crispum",
  timeToSow: "spring",
  directSowing: true,
  developmentTime: 70,
  waterDemand:	"medium",
  nutritionalNeeds: "small",
  perennial: true, 
},
{
  name: "Chives",
  category:	"Herbs",
  scientificName:	"Allium schoenoprasum",
  timeToSow: "spring",
  directSowing: false,
  developmentTime: 80,
  waterDemand:	"small",
  nutritionalNeeds: "small",
  perennial: true, 
},
{
  name: "Rosemary",
  category:	"Herbs",
  scientificName:	"Rosmarinus officinalis",
  timeToSow: "spring",
  directSowing: false,
  developmentTime: 60,
  waterDemand:	"small",
  nutritionalNeeds: "small",
  perennial: true, 
},
{
  name: "Basil",
  category:	"Herbs",
  scientificName:	"Ocimum basilicum",
  timeToSow: "spring",
  directSowing: true,
  developmentTime: 30,
  waterDemand:	"high",
  nutritionalNeeds: "small",
  perennial: false, 
},
]

const berriesAndFruit = [
  {
    name: "Apple",
    category:	"Fruits/berries",
    scientificName:	"Malum",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 2000,
    waterDemand:	"medium",
    nutritionalNeeds: "medium",
    perennial: true, 
  },
  {
    name: "Strawberry",
    category:	"Fruits/berries",
    scientificName:	"Fragaria ananassa",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 730,
    waterDemand:	"medium",
    nutritionalNeeds: "small",
    perennial: true, 
  },
  {
    name: "Raspberry",
    category:	"Rubus idaeus",
    scientificName:	"Allium cepa",
    timeToSow: "autumn",
    directSowing: false,
    developmentTime: 365,
    waterDemand:	"medium",
    nutritionalNeeds: "small",
    perennial: true, 
  },
  {
    name: "Blackberry",
    category:	"Fruits/berries",
    scientificName:	"Rubus",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 365,
    waterDemand:	"medium",
    nutritionalNeeds: "medium",
    perennial: true, 
  },
  ]
