const vegetables = [
  {
    name: "Carrot",
    category: "vegetables",
    scientificName: "Daucus carota",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 80,
    waterDemand: "high",
    nutritionalNeeds: "small",
    perennial: false,
    img: "./assets/carrots.jpg",
  },
  {
    name: "Zucchini",
    category: "vegetables",
    scientificName: "Cucurbita pepo",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 75,
    waterDemand: "medium",
    nutritionalNeeds: "medium",
    perennial: false,
    img: "./assets/zucchini-1.jpg",
  },
  {
    name: "Onion",
    category: "vegetables",
    scientificName: "Allium cepa",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 110,
    waterDemand: "medium",
    nutritionalNeeds: "medium",
    perennial: false,
    img: "./assets/onions.jpg",
  },
  {
    name: "Garlic",
    category: "vegetables",
    scientificName: "Alium sativum",
    timeToSow: "autumn",
    directSowing: true,
    developmentTime: 300,
    waterDemand: "high",
    nutritionalNeeds: "high",
    perennial: false,
    img: "./assets/garlic.jpg",
  },
];

const herbs = [
  {
    name: "Parsley",
    category: "herbs",
    scientificName: "Petroselinum crispum",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 70,
    waterDemand: "medium",
    nutritionalNeeds: "small",
    perennial: true,
    img: "./assets/parsley.jpg",
  },
  {
    name: "Chives",
    category: "herbs",
    scientificName: "Allium schoenoprasum",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 80,
    waterDemand: "small",
    nutritionalNeeds: "small",
    perennial: true,
    img: "./assets/chives.jpg",
  },
  {
    name: "Rosemary",
    category: "herbs",
    scientificName: "Rosmarinus officinalis",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 60,
    waterDemand: "small",
    nutritionalNeeds: "small",
    perennial: true,
    img: "./assets/rosemary.jpg",
  },
  {
    name: "Basil",
    category: "herbs",
    scientificName: "Ocimum basilicum",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 30,
    waterDemand: "high",
    nutritionalNeeds: "small",
    perennial: false,
    img: "./assets/basil.jpg",
  },
];

const berriesAndFruit = [
  {
    name: "Apple",
    category: "fruits/berries",
    scientificName: "Malum",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 2000,
    waterDemand: "medium",
    nutritionalNeeds: "medium",
    perennial: true,
    img: "./assets/apples.jpg",
  },
  {
    name: "Strawberry",
    category: "fruits/berries",
    scientificName: "Fragaria ananassa",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 730,
    waterDemand: "medium",
    nutritionalNeeds: "small",
    perennial: true,
    img: "./assets/strawberries-2.jpg",
  },
  {
    name: "Wild strawberries",
    category: "fruits/berries",
    scientificName: "Fragaria vesca",
    timeToSow: "spring",
    directSowing: true,
    developmentTime: 140,
    waterDemand: "medium",
    nutritionalNeeds: "medium",
    perennial: true,
    img: "./assets/wild-strawberries.jpg",
  },
  {
    name: "Blackberry",
    category: "fruits/berries",
    scientificName: "Rubus",
    timeToSow: "spring",
    directSowing: false,
    developmentTime: 365,
    waterDemand: "medium",
    nutritionalNeeds: "medium",
    perennial: true,
    img: "./assets/wild-strawberries.jpg",
  },
];
